# Managed by Multi Agent Governance – this file is the SSOT for MCP routing.
#
# Values may reference environment variables using ${VAR} or ${VAR:-default}
# expansion. Secrets and tokens belong in .mcp/.env.mcp (ignored by git).

env:
  files:
    - .mcp/.env.mcp

router:
  provider: ${MCP_ROUTER_PROVIDER:-dummy}
  max_sessions: ${MCP_MAX_SESSIONS:-5}
  request_timeout_sec: ${MCP_REQUEST_TIMEOUT_SEC:-30}
  max_retries: ${MCP_MAX_RETRIES:-1}
  backoff_base_sec: ${MCP_BACKOFF_BASE_SEC:-0.5}
  log_flush_every: ${MCP_LOG_FLUSH_EVERY:-50}

providers:
  dummy:
    type: dummy
  openai:
    type: openai
    api_key: ${OPENAI_API_KEY}
  github:
    type: github
    token: ${GITHUB_TOKEN}
    base_url: ${GITHUB_API_BASE:-https://api.github.com}
    timeout_sec: ${GITHUB_TIMEOUT_SEC:-15}
    api_version: ${GITHUB_API_VERSION:-2022-11-28}

servers:
  context7:
    transport: http
    url: ${CONTEXT7_MCP_URL:-https://mcp.context7.com/mcp}
    metadata:
      api_url: ${CONTEXT7_API_URL:-https://context7.com/api/v1}
  everything:
    transport: stdio
    command:
      program: npx
      args:
        - "-y"
        - "@modelcontextprotocol/server-everything"
    metadata:
      docs: https://github.com/modelcontextprotocol/servers/tree/main/src/everything
  fetch:
    transport: stdio
    command:
      program: uvx
      args:
        - "mcp-server-fetch"
    metadata:
      docs: https://github.com/modelcontextprotocol/servers/tree/main/src/fetch
  filesystem:
    transport: stdio
    command:
      program: npx
      args:
        - "-y"
        - "@modelcontextprotocol/server-filesystem"
        - ${MCP_FILESYSTEM_ROOT:-.}
    metadata:
      docs: https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem
      notes: requires read/write access to configured directories
  git:
    transport: stdio
    command:
      program: uvx
      args:
        - "mcp-server-git"
        - "--repository"
        - ${MCP_GIT_REPOSITORY:-.}
    metadata:
      docs: https://github.com/modelcontextprotocol/servers/tree/main/src/git
  memory:
    transport: stdio
    command:
      program: npx
      args:
        - "-y"
        - "@modelcontextprotocol/server-memory"
    metadata:
      docs: https://github.com/modelcontextprotocol/servers/tree/main/src/memory
  sequentialthinking:
    transport: stdio
    command:
      program: npx
      args:
        - "-y"
        - "@modelcontextprotocol/server-sequential-thinking"
    metadata:
      docs: https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking
  serena:
    transport: stdio
    command:
      program: uvx
      args:
        - --from
        - git+https://github.com/oraios/serena
        - serena
        - start-mcp-server
        - --context
        - ${SERENA_CONTEXT:-ide-assistant}
        - --project
        - ${SERENA_PROJECT_ROOT:-.}
    metadata:
      docs: https://github.com/oraios/serena
      registry: https://github.com/mcp/oraios/serena
  time:
    transport: stdio
    command:
      program: uvx
      args:
        - "mcp-server-time"
    metadata:
      docs: https://github.com/modelcontextprotocol/servers/tree/main/src/time
