name: Contracts Check
on: [push, pull_request]
jobs:
  contracts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jsonschema
      - name: Validate JSON Schemas
        run: |
          python - <<'PY'
          import json, glob, sys
          from jsonschema import Draft202012Validator
          ok=True
          for path in glob.glob("contracts/**/*.json", recursive=True):
            try:
              with open(path) as f: schema=json.load(f)
              Draft202012Validator.check_schema(schema)
              print("OK:", path)
            except Exception as e:
              ok=False; print("INVALID:", path, e)
          sys.exit(0 if ok else 1)
          PY
