name: Validate SOP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-sop:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Debug environment
      run: |
        echo "Python version:"
        python3 --version
        echo "Current directory:"
        pwd
        echo "Script exists:"
        ls -la src/automation/scripts/validate_sop.py
        
    - name: Run SOP validation
      run: |
        cd /home/runner/work/multi-agent-governance/multi-agent-governance
        python3 src/automation/scripts/validate_sop.py
